name: Linters

on:
  pull_request:

jobs:
  commitizen:
    uses: janw/workflows/.github/workflows/commitizen.yaml@main

  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v3

      - name: Install poetry
        run: pipx install pre-commit

      - id: cache-restore
        uses: actions/cache/restore@v4
        with:
          path: ~/.cache/pre-commit
          key: pre-commit-v0|${{ hashFiles('.pre-commit-config.yaml') }}

      - run: pre-commit run --show-diff-on-failure --color=always --all-files
        shell: bash

      - id: cache-save
        uses: actions/cache/save@v4
        if: always() && steps.cache-restore.outputs.cache-hit != 'true'
        with:
          key: ${{ steps.cache-restore.outputs.cache-primary-key }}
          path: ~/.cache/pre-commit
